#Requires -Version 5.1
<#
.SYNOPSIS
    Generates terraform.tfvars for each enabled cloud from .env + the region
    selection produced by scripts/02-select-regions.ps1, then runs
    terraform init/validate/plan (saved plan file) for every enabled cloud
    root plus terraform/environments/demo.

.DESCRIPTION
    Never applies anything - only produces saved plan files
    (terraform/<cloud>/tfplan, gitignored) for scripts/04-apply.ps1 to apply
    later. Safe to re-run at any time; regenerates terraform.tfvars and the
    plan file fresh each run.
#>
[CmdletBinding()]
param()

. (Join-Path (Join-Path $PSScriptRoot "lib") "common.ps1")

$dotEnv = Get-DotEnv
$enabledClouds = Get-EnabledClouds -DotEnv $dotEnv
$regionSelection = Read-RegionSelection
if (-not $regionSelection) {
    Write-WarnMsg "artifacts/region-selection.json not found - run scripts/02-select-regions.ps1 first. Continuing with each root's variables.tf default region."
}

function New-TfVarsFile {
    param(
        [Parameter(Mandatory)][string]$Cloud,
        [Parameter(Mandatory)][string]$RootDir,
        [Parameter(Mandatory)][hashtable]$Lines
    )
    $path = Join-Path $RootDir "terraform.tfvars"
    $content = @(
        "# Auto-generated by scripts/03-init-plan.ps1 from .env + artifacts/region-selection.json."
        "# Safe to delete/regenerate - gitignored, never checked in. Edit .env instead of this file."
        ""
    )
    foreach ($key in $Lines.Keys) {
        $value = $Lines[$key]
        if ($null -eq $value -or $value -eq "") { continue }
        if ($value -is [bool]) {
            $content += "$key = $($value.ToString().ToLowerInvariant())"
        } elseif ($value -is [int] -or $value -is [double]) {
            $content += "$key = $value"
        } else {
            $escaped = $value -replace '"', '\"'
            $content += "$key = `"$escaped`""
        }
    }
    Set-Content -Path $path -Value $content -Encoding utf8
    Write-Ok "Wrote $path"
}

function Invoke-TerraformRoot {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][string]$RootDir
    )
    Write-Step "terraform init/validate/plan: $Label ($RootDir)"
    Push-Location $RootDir
    try {
        terraform fmt | Out-Null
        Invoke-Checked -Command "terraform" -Arguments @("init", "-input=false") -ErrorContext "$Label init"
        Invoke-Checked -Command "terraform" -Arguments @("validate") -ErrorContext "$Label validate"
        Invoke-Checked -Command "terraform" -Arguments @("plan", "-input=false", "-out=tfplan") -ErrorContext "$Label plan"
        Write-Ok "$Label : plan saved to $(Join-Path $RootDir 'tfplan')"
    } finally {
        Pop-Location
    }
}

$tfRoot = Get-TerraformDir

# --- Azure -----------------------------------------------------------------------
if ($enabledClouds -contains "azure") {
    $region = if ($regionSelection -and $regionSelection.azure) { $regionSelection.azure.selected } else { $null }
    New-TfVarsFile -Cloud "azure" -RootDir (Join-Path $tfRoot "azure") -Lines @{
        owner                    = Get-EnvValue -DotEnv $dotEnv -Key "OWNER"
        project                  = Get-EnvValue -DotEnv $dotEnv -Key "PROJECT" -Default "fleet-arc-demo"
        environment              = Get-EnvValue -DotEnv $dotEnv -Key "ENVIRONMENT" -Default "demo"
        expiration_date          = Get-EnvValue -DotEnv $dotEnv -Key "EXPIRATION_DATE"
        location                 = $region
        expected_tenant_id       = Get-EnvValue -DotEnv $dotEnv -Key "AZURE_EXPECTED_TENANT_ID"
        expected_subscription_id = Get-EnvValue -DotEnv $dotEnv -Key "AZURE_EXPECTED_SUBSCRIPTION_ID"
    }
    Invoke-TerraformRoot -Label "azure" -RootDir (Join-Path $tfRoot "azure")
}

# --- AWS -------------------------------------------------------------------------
if ($enabledClouds -contains "aws") {
    $region = if ($regionSelection -and $regionSelection.aws) { $regionSelection.aws.selected } else { $null }
    New-TfVarsFile -Cloud "aws" -RootDir (Join-Path $tfRoot "aws") -Lines @{
        owner               = Get-EnvValue -DotEnv $dotEnv -Key "OWNER"
        project             = Get-EnvValue -DotEnv $dotEnv -Key "PROJECT" -Default "fleet-arc-demo"
        environment         = Get-EnvValue -DotEnv $dotEnv -Key "ENVIRONMENT" -Default "demo"
        expiration_date     = Get-EnvValue -DotEnv $dotEnv -Key "EXPIRATION_DATE"
        region              = $region
        aws_profile         = Get-EnvValue -DotEnv $dotEnv -Key "AWS_PROFILE"
        aws_assume_role_arn = Get-EnvValue -DotEnv $dotEnv -Key "AWS_ASSUME_ROLE_ARN"
        expected_account_id = Get-EnvValue -DotEnv $dotEnv -Key "AWS_EXPECTED_ACCOUNT_ID"
    }
    Invoke-TerraformRoot -Label "aws" -RootDir (Join-Path $tfRoot "aws")
}

# --- GCP -------------------------------------------------------------------------
if ($enabledClouds -contains "gcp") {
    $region = if ($regionSelection -and $regionSelection.gcp) { $regionSelection.gcp.selected_region } else { $null }
    $zone = if ($regionSelection -and $regionSelection.gcp) { $regionSelection.gcp.selected_zone } else { $null }
    New-TfVarsFile -Cloud "gcp" -RootDir (Join-Path $tfRoot "gcp") -Lines @{
        owner                           = Get-EnvValue -DotEnv $dotEnv -Key "OWNER"
        project                         = Get-EnvValue -DotEnv $dotEnv -Key "PROJECT" -Default "fleet-arc-demo"
        environment                     = Get-EnvValue -DotEnv $dotEnv -Key "ENVIRONMENT" -Default "demo"
        expiration_date                 = Get-EnvValue -DotEnv $dotEnv -Key "EXPIRATION_DATE"
        project_id                      = Get-EnvValue -DotEnv $dotEnv -Key "GCP_PROJECT_ID"
        region                          = $region
        zone                            = $zone
        gcp_impersonate_service_account = Get-EnvValue -DotEnv $dotEnv -Key "GCP_IMPERSONATE_SERVICE_ACCOUNT"
    }
    Invoke-TerraformRoot -Label "gcp" -RootDir (Join-Path $tfRoot "gcp")
}

# --- environments/demo (always - needs no cloud credentials) -----------------
Invoke-TerraformRoot -Label "environments/demo" -RootDir (Join-Path (Join-Path $tfRoot "environments") "demo")

Write-Step "Summary"
Write-Ok "Plans saved for: $($enabledClouds -join ', '), environments/demo"
Write-Info "Next: scripts/04-apply.ps1 to apply these saved plans (this creates real, billable cloud resources)."
exit 0
